
USE GOSALES_OLTP;

DROP DATABASE GOSALESDW_OLAP;

CREATE DATABASE GOSALESDW_OLAP;

USE GOSALESDW_OLAP;

IF OBJECT_ID('FACT_PRODUCT_PERFORMANCE', 'U') IS NOT NULL
    DROP TABLE FACT_PRODUCT_PERFORMANCE;
IF OBJECT_ID('PRODUCT_DIMENSION', 'U') IS NOT NULL
    DROP TABLE PRODUCT_DIMENSION;
IF OBJECT_ID('TIME_DIMENSION', 'U') IS NOT NULL
    DROP TABLE [TIME_DIMENSION];

CREATE TABLE PRODUCT_DIMENSION (
    PRODUCT_LINE_CODE NVARCHAR(50),
    PRODUCT_LINE_DESC NVARCHAR(255),
    PRODUCT_TYPE_CODE NVARCHAR(50),
    PRODUCT_TYPE_DESC NVARCHAR(255),
    PRODUCT_NUMBER INT PRIMARY KEY,
    PRODUCT_NAME NVARCHAR(255),
    PRODUCT_DESCRIPTION NVARCHAR(MAX),
    BASE_PRODUCT_NUMBER INT,
    PRODUCT_BRAND_CODE NVARCHAR(50),
    PRODUCT_BRAND_EN NVARCHAR(255)
);

CREATE TABLE TIME_DIMENSION(
	[DAY_KEY] [int] NOT NULL PRIMARY KEY,
	[DAY_DATE] [datetime] NULL,
	[MONTH_KEY] [int] NOT NULL,
	[CURRENT_MONTH] [smallint] NOT NULL,
	[MONTH_NUMBER] [int] NOT NULL,
	[QUARTER_KEY] [int] NOT NULL,
	[CURRENT_QUARTER] [smallint] NOT NULL,
	[CURRENT_YEAR] [smallint] NOT NULL,
	[DAY_OF_WEEK] [smallint] NOT NULL,
	[DAY_OF_MONTH] [smallint] NOT NULL,
	[DAYS_IN_MONTH] [smallint] NOT NULL,
	[DAY_OF_YEAR] [smallint] NOT NULL,
	[WEEK_OF_MONTH] [smallint] NOT NULL,
	[WEEK_OF_QUARTER] [smallint] NOT NULL,
	[WEEK_OF_YEAR] [smallint] NOT NULL,
	[MONTH_EN] [nvarchar](25) NOT NULL,
	[WEEKDAY_EN] [nvarchar](20) NOT NULL,
	[MONTH_DE] [nvarchar](25) NOT NULL,
	[WEEKDAY_DE] [nvarchar](20) NOT NULL,
	[MONTH_FR] [nvarchar](25) NOT NULL,
	[WEEKDAY_FR] [nvarchar](20) NOT NULL,
	[MONTH_JA] [nvarchar](25) NOT NULL,
	[WEEKDAY_JA] [nvarchar](20) NOT NULL,
	[MONTH_AR] [nvarchar](25) NOT NULL,
	[WEEKDAY_AR] [nvarchar](20) NOT NULL,
	[MONTH_CS] [nvarchar](25) NOT NULL,
	[WEEKDAY_CS] [nvarchar](20) NOT NULL,
	[MONTH_DA] [nvarchar](25) NOT NULL,
	[WEEKDAY_DA] [nvarchar](20) NOT NULL,
	[MONTH_EL] [nvarchar](25) NOT NULL,
	[WEEKDAY_EL] [nvarchar](20) NOT NULL,
	[MONTH_ES] [nvarchar](25) NOT NULL,
	[WEEKDAY_ES] [nvarchar](20) NOT NULL,
	[MONTH_FI] [nvarchar](25) NOT NULL,
	[WEEKDAY_FI] [nvarchar](20) NOT NULL,
	[MONTH_HR] [nvarchar](25) NOT NULL,
	[WEEKDAY_HR] [nvarchar](20) NOT NULL,
	[MONTH_HU] [nvarchar](25) NOT NULL,
	[WEEKDAY_HU] [nvarchar](20) NOT NULL,
	[MONTH_ID] [nvarchar](25) NOT NULL,
	[WEEKDAY_ID] [nvarchar](20) NOT NULL,
	[MONTH_IT] [nvarchar](25) NOT NULL,
	[WEEKDAY_IT] [nvarchar](20) NOT NULL,
	[MONTH_KK] [nvarchar](25) NOT NULL,
	[WEEKDAY_KK] [nvarchar](20) NOT NULL,
	[MONTH_KO] [nvarchar](25) NOT NULL,
	[WEEKDAY_KO] [nvarchar](20) NOT NULL,
	[MONTH_MS] [nvarchar](25) NOT NULL,
	[WEEKDAY_MS] [nvarchar](20) NOT NULL,
	[MONTH_NL] [nvarchar](25) NOT NULL,
	[WEEKDAY_NL] [nvarchar](20) NOT NULL,
	[MONTH_NO] [nvarchar](25) NOT NULL,
	[WEEKDAY_NO] [nvarchar](20) NOT NULL,
	[MONTH_PL] [nvarchar](25) NOT NULL,
	[WEEKDAY_PL] [nvarchar](20) NOT NULL,
	[MONTH_PT] [nvarchar](25) NOT NULL,
	[WEEKDAY_PT] [nvarchar](20) NOT NULL,
	[MONTH_RO] [nvarchar](25) NOT NULL,
	[WEEKDAY_RO] [nvarchar](20) NOT NULL,
	[MONTH_RU] [nvarchar](25) NOT NULL,
	[WEEKDAY_RU] [nvarchar](20) NOT NULL,
	[MONTH_SC] [nvarchar](25) NOT NULL,
	[WEEKDAY_SC] [nvarchar](20) NOT NULL,
	[MONTH_SL] [nvarchar](25) NOT NULL,
	[WEEKDAY_SL] [nvarchar](20) NOT NULL,
	[MONTH_SV] [nvarchar](25) NOT NULL,
	[WEEKDAY_SV] [nvarchar](20) NOT NULL,
	[MONTH_TC] [nvarchar](25) NOT NULL,
	[WEEKDAY_TC] [nvarchar](20) NOT NULL,
	[MONTH_TH] [nvarchar](25) NOT NULL,
	[WEEKDAY_TH] [nvarchar](20) NOT NULL,
	[MONTH_TR] [nvarchar](25) NOT NULL,
	[WEEKDAY_TR] [nvarchar](20) NOT NULL,
);

CREATE TABLE FACT_PRODUCT_PERFORMANCE (
	PERFORMANCE_ID INT PRIMARY KEY IDENTITY(1,1),
    ORDER_NUMBER INT,
    ORDER_DATE DATE,
    DAY_KEY INT,
    PRODUCT_NUMBER INT,
    QUANTITY INT,
    UNIT_COST DECIMAL(10, 2),
    UNIT_PRICE DECIMAL(10, 2),
    UNIT_SALE_PRICE DECIMAL(10, 2),
    REVENUE DECIMAL(10, 2),
	CONSTRAINT FK_Fact_Order_Product FOREIGN KEY (PRODUCT_NUMBER) REFERENCES PRODUCT_DIMENSION(PRODUCT_NUMBER),
	CONSTRAINT FK_Fact_Order_Time FOREIGN KEY (DAY_KEY) REFERENCES TIME_DIMENSION(DAY_KEY)
);

INSERT INTO PRODUCT_DIMENSION (
    PRODUCT_LINE_CODE, 
    PRODUCT_LINE_DESC, 
    PRODUCT_TYPE_CODE, 
    PRODUCT_TYPE_DESC, 
    PRODUCT_NUMBER, 
    PRODUCT_NAME, 
    PRODUCT_DESCRIPTION, 
    BASE_PRODUCT_NUMBER, 
    PRODUCT_BRAND_CODE, 
    PRODUCT_BRAND_EN
)
SELECT [GOSALES_OLTP].[gosales].[PRODUCT_LINE].[PRODUCT_LINE_CODE]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT_LINE].[PRODUCT_LINE_EN] AS [PRODUCT_LINE_DESC]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_TYPE_CODE]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT_TYPE].[PRODUCT_TYPE_EN] AS [PRODUCT_TYPE_DESC]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_NUMBER]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT_NAME_LOOKUP].[PRODUCT_NAME]
      ,[GOSALES_OLTP].[gosales].[PRODUCT_NAME_LOOKUP].[PRODUCT_DESCRIPTION]
      ,[GOSALES_OLTP].[gosales].[PRODUCT].[BASE_PRODUCT_NUMBER]
      ,[GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_BRAND_CODE]
	  ,[GOSALES_OLTP].[gosales].[PRODUCT_BRAND].[PRODUCT_BRAND_EN]

  FROM [GOSALES_OLTP].[gosales].[PRODUCT], [GOSALES_OLTP].[gosales].[PRODUCT_BRAND], [GOSALES_OLTP].[gosales].[PRODUCT_TYPE],[GOSALES_OLTP].[gosales].[PRODUCT_NAME_LOOKUP],[GOSALES_OLTP].[gosales].[PRODUCT_LINE]
  WHERE [GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_BRAND_CODE] = [GOSALES_OLTP].[gosales].[PRODUCT_BRAND].[PRODUCT_BRAND_CODE]
	AND [GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_TYPE_CODE] = [GOSALES_OLTP].[gosales].[PRODUCT_TYPE].[PRODUCT_TYPE_CODE]
	AND [GOSALES_OLTP].[gosales].[PRODUCT_LINE].[PRODUCT_LINE_CODE] = [GOSALES_OLTP].[gosales].[PRODUCT_TYPE].[PRODUCT_LINE_CODE]
	AND [GOSALES_OLTP].[gosales].[PRODUCT].[PRODUCT_NUMBER] = [GOSALES_OLTP].[gosales].[PRODUCT_NAME_LOOKUP].[PRODUCT_NUMBER]
	AND [GOSALES_OLTP].[gosales].[PRODUCT_NAME_LOOKUP].[PRODUCT_LANGUAGE] = 'EN'

INSERT INTO TIME_DIMENSION(
    DAY_KEY, DAY_DATE, MONTH_KEY, CURRENT_MONTH, MONTH_NUMBER, QUARTER_KEY, CURRENT_QUARTER, CURRENT_YEAR, DAY_OF_WEEK, DAY_OF_MONTH, DAYS_IN_MONTH, DAY_OF_YEAR, WEEK_OF_MONTH, WEEK_OF_QUARTER, WEEK_OF_YEAR, MONTH_EN, WEEKDAY_EN, MONTH_DE, WEEKDAY_DE, MONTH_FR, WEEKDAY_FR, MONTH_JA, WEEKDAY_JA, MONTH_AR, WEEKDAY_AR, MONTH_CS, WEEKDAY_CS, MONTH_DA, WEEKDAY_DA, MONTH_EL, WEEKDAY_EL, MONTH_ES, WEEKDAY_ES, MONTH_FI, WEEKDAY_FI, MONTH_HR, WEEKDAY_HR, MONTH_HU, WEEKDAY_HU, MONTH_ID, WEEKDAY_ID, MONTH_IT, WEEKDAY_IT, MONTH_KK, WEEKDAY_KK, MONTH_KO, WEEKDAY_KO, MONTH_MS, WEEKDAY_MS, MONTH_NL, WEEKDAY_NL, MONTH_NO, WEEKDAY_NO, MONTH_PL, WEEKDAY_PL, MONTH_PT, WEEKDAY_PT, MONTH_RO, WEEKDAY_RO, MONTH_RU, WEEKDAY_RU, MONTH_SC, WEEKDAY_SC, MONTH_SL, WEEKDAY_SL, MONTH_SV, WEEKDAY_SV, MONTH_TC, WEEKDAY_TC, MONTH_TH, WEEKDAY_TH, MONTH_TR, WEEKDAY_TR
)
SELECT DAY_KEY, DAY_DATE, MONTH_KEY, CURRENT_MONTH, MONTH_NUMBER, QUARTER_KEY, CURRENT_QUARTER, CURRENT_YEAR, DAY_OF_WEEK, DAY_OF_MONTH, DAYS_IN_MONTH, DAY_OF_YEAR, WEEK_OF_MONTH, WEEK_OF_QUARTER, WEEK_OF_YEAR, MONTH_EN, WEEKDAY_EN, MONTH_DE, WEEKDAY_DE, MONTH_FR, WEEKDAY_FR, MONTH_JA, WEEKDAY_JA, MONTH_AR, WEEKDAY_AR, MONTH_CS, WEEKDAY_CS, MONTH_DA, WEEKDAY_DA, MONTH_EL, WEEKDAY_EL, MONTH_ES, WEEKDAY_ES, MONTH_FI, WEEKDAY_FI, MONTH_HR, WEEKDAY_HR, MONTH_HU, WEEKDAY_HU, MONTH_ID, WEEKDAY_ID, MONTH_IT, WEEKDAY_IT, MONTH_KK, WEEKDAY_KK, MONTH_KO, WEEKDAY_KO, MONTH_MS, WEEKDAY_MS, MONTH_NL, WEEKDAY_NL, MONTH_NO, WEEKDAY_NO, MONTH_PL, WEEKDAY_PL, MONTH_PT, WEEKDAY_PT, MONTH_RO, WEEKDAY_RO, MONTH_RU, WEEKDAY_RU, MONTH_SC, WEEKDAY_SC, MONTH_SL, WEEKDAY_SL, MONTH_SV, WEEKDAY_SV, MONTH_TC, WEEKDAY_TC, MONTH_TH, WEEKDAY_TH, MONTH_TR, WEEKDAY_TR
FROM [GOSALES_OLTP].[gosales].TIME_DIMENSION	

INSERT INTO FACT_PRODUCT_PERFORMANCE (
	ORDER_NUMBER,
	ORDER_DATE,
	DAY_KEY,
	PRODUCT_NUMBER,
	QUANTITY,
	UNIT_COST,
	UNIT_PRICE,
	UNIT_SALE_PRICE,
	REVENUE)
SELECT [GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_NUMBER]
      ,[GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_DATE]
	  ,YEAR([GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_DATE])*10000 + MONTH([GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_DATE])*100 + DAY([GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_DATE]) AS DAY_KEY
	  ,[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[PRODUCT_NUMBER]
	  ,[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[QUANTITY]
      ,[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[UNIT_COST]
      ,[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[UNIT_PRICE]
      ,[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[UNIT_SALE_PRICE]
	  , [GOSALES_OLTP].[gosales].[ORDER_DETAILS].[UNIT_SALE_PRICE] * [GOSALES_OLTP].[gosales].[ORDER_DETAILS].[QUANTITY] AS REVENUE
  FROM [GOSALES_OLTP].[gosales].[ORDER_HEADER],[GOSALES_OLTP].[gosales].[ORDER_DETAILS]
  WHERE [GOSALES_OLTP].[gosales].[ORDER_HEADER].[ORDER_NUMBER] =[GOSALES_OLTP].[gosales].[ORDER_DETAILS].[ORDER_NUMBER]

WITH RevenuePerYear AS (
    SELECT
        p.PRODUCT_NUMBER,
        YEAR(t.DAY_DATE) AS Year,
        SUM(f.REVENUE) AS TotalRevenue
    FROM FACT_PRODUCT_PERFORMANCE f
    JOIN TIME_DIMENSION t ON f.DAY_KEY = t.DAY_KEY
    JOIN PRODUCT_DIMENSION p ON f.PRODUCT_NUMBER = p.PRODUCT_NUMBER
    GROUP BY p.PRODUCT_NUMBER, YEAR(t.DAY_DATE)
),
RevenueGrowth AS (
    SELECT
        r1.PRODUCT_NUMBER,
        r1.Year AS CurrentYear,
        r1.TotalRevenue AS CurrentYearRevenue,
        r2.Year AS PreviousYear,
        r2.TotalRevenue AS PreviousYearRevenue,
        CASE 
            WHEN r2.TotalRevenue IS NULL THEN NULL
            ELSE ROUND(((r1.TotalRevenue - r2.TotalRevenue) / r2.TotalRevenue) * 100, 2)
        END AS GrowthPercentage
    FROM RevenuePerYear r1
    LEFT JOIN RevenuePerYear r2
        ON r1.PRODUCT_NUMBER = r2.PRODUCT_NUMBER
        AND r1.Year = r2.Year + 1
)
SELECT
    p.PRODUCT_NUMBER,
    p.PRODUCT_NAME,
    rg.CurrentYear,
    rg.CurrentYearRevenue,
    CASE 
        WHEN rg.PreviousYear IS NULL THEN 'N/A'
        ELSE CAST(rg.PreviousYear AS NVARCHAR)
    END AS PreviousYear,
    COALESCE(rg.PreviousYearRevenue, 0) AS PreviousYearRevenue,
    CASE
        WHEN rg.GrowthPercentage IS NULL THEN 'no prior data'
        ELSE FORMAT(rg.GrowthPercentage, 'N2')
    END AS GrowthPercentage
FROM RevenueGrowth rg
JOIN PRODUCT_DIMENSION p ON rg.PRODUCT_NUMBER = p.PRODUCT_NUMBER
ORDER BY p.PRODUCT_NUMBER, rg.CurrentYear;
